##
## Makefile for Makefile in /home/platel_k//projet/piscine/Jour_12
## 
## Made by kevin platel
## Login   <platel_k@epitech.net>
## 
## Started on  Tue Oct 25 10:18:29 2011 kevin platel
## Last update Tue Oct 25 19:48:39 2011 kevin platel
##

NAME	= test

SRC	=main.c \
	my_params_in_list.c \
	my_show_list.c \
	my_list_size.c \
	my_rev_list.c \
	my_put_elem_in_sort_list.c

all:	$(NAME)

$(NAME):	
	cc -I ~/lib/ -o $(NAME) $(SRC) -L ~/lib -lmy

clean:
	rm -f $(NAME)