##
## Makefile for Makefile in /home/platel_k/projet/minilibX/tp1
##
## Made by kevin platel
## Login   <platel_k@epitech.net>
##
## Started on  Wed Nov  9 12:58:27 2011 kevin platel
##

all:
	make -C client/
	make -C server/
clean:
	make clean -C client/
	make clean -C server/
fclean:
	make fclean -C client/
	make fclean -C server/

re: 	fclean all