##
## Makefile for Makefile in /home/platel_k//projet/piscine/Jour_11/do-op
## 
## Made by kevin platel
## Login   <platel_k@epitech.net>
## 
## Started on  Mon Oct 24 10:56:09 2011 kevin platel
## Last update Mon Oct 24 14:47:13 2011 kevin platel
##

NAME	= do-op

LIB	= ~/lib -lmy

HEAD	= .

$(NAME):
	cc -o $(NAME) *.c -L $(LIB) 

clean:
	rm -f 